<Login>:
    md_bg_color: [253/255, 253/255, 253/255, 1]
    
    MDCard:
        size_hint: None, None
        size: 320, 400
        pos_hint: {"center_x":.5, "center_y":.5}
        elevation: 15
        md_bg_color: [253/255, 240/255, 250/255, 1]
        padding: 20
        spacing: 30
        orientation: 'vertical'
        
        MDLabel: 
            text: 'LOGIN'
            font_style: 'Button'
            font_size: 45
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 15
            
        MDTextField:
            id: login
            hint_text: 'Login'
            icon_right: 'account'
            size_hint_x: None
            width: 220
            font_size: 20
            pos_hint: {"center_x": .5}
            color_active: [.99, .99, 1, 1]
            
        MDTextField:
            id: senha
            hint_text: 'Senha'
            icon_right: 'eye-off'
            size_hint_x: None
            width: 220
            font_size: 20
            pos_hint: {"center_x": .5}
            color_active: [.99, .99, 1, 1]
            password: True
        
        MDLabel:
            id: on_error 
            text: ''
            font_style: 'Caption'
            font_size: 15
            color: .9, .34, .43, 1
            halign: 'center'
            size_hint_y: None
            height: self.texture_size[1]
            padding_y: 15
            
        MDRoundFlatButton:
            text: 'ENTRAR'
            pos_hint: {"center_x": .5}
            font_size: 15
            on_release: root.do_login()
            
        Widget:
            size_hint_y: None
            height: 30
