<Medicamentos>:
    name: "medicamentos"
    MDBoxLayout:
        size_hint: 1,1
        padding: 20
        spacing: 40
        canvas:
            Color:
                rgba: 1,.5,.3,1
            Rectangle:
                pos: self.pos
                size: self.size
        orientation:'vertical'
        BarraVoltar:
            id: title
        MDSeparator:
            canvas:
                Color:
                    rgba: 1,.8,.3,1
                Rectangle:
                    pos: self.pos
                    size: self.size

        MDBoxLayout:
            canvas:
                Color:
                    rgba: 1,.2,.6,1
                Rectangle:
                    pos: self.pos
                    size: self.size
            adaptive_height: True
            spacing: dp(30)
            padding: 15, 15, 15, 15

            Field:
                valor: 'Código'
                tamanho: '150dp'
            Field:
                valor: 'Nome'
                tamanho: '250dp'
            Field:
                id: validade
                valor: "Validade"
                tamanho: '100dp'
                on_focus: root.show_date_picker()
        MDBoxLayout:
            canvas:
                Color:
                    rgba: 1,.2,.1,1
                Rectangle:
                    pos: self.pos
                    size: self.size
            adaptive_height: True
            spacing: dp(30)
            padding: 5, 5, 5, 5
            Field:
                valor: 'Princípio Ativo'
                tamanho: "150dp"
            Field:
                valor: 'Dosagem'
                tamanho: '60dp'
            MDDropDownItem:
                id: drop_item
                pos_hint: {'center_x': .5, 'center_y': .5}
                text: 'Unidade'
                #on_release: self.set_item("New Item")
        MDBoxLayout:
            canvas:
                Color:
                    rgba: 1,.2,.6,1
                Rectangle:
                    pos: self.pos
                    size: self.size
            adaptive_height: True
            spacing: dp(30)
            padding: 5, 5, 5, 5
            Field:
                valor: 'Laboratório'
            Field:
                valor: 'Registro MS'
            MDDropDownItem:
                id: drop_item
                pos_hint: {'center_x': .5, 'center_y': .5}
                text: 'Tarja'
                #on_release: self.set_item("New Item")
        MDBoxLayout:
            canvas:
                Color:
                    rgba: 1,.2,.6,1
                Rectangle:
                    pos: self.pos
                    size: self.size
            adaptive_height: True
            spacing: dp(30)
            padding: 5, 5, 5, 5
            Field:
                valor: 'Estoque Físico'
            Field:
                valor: 'Preço'
        BoxLayout:
            canvas:
                Color:
                    rgba: 1,.2,.6,1
                Rectangle:
                    pos: self.pos
                    size: self.size
            spacing: dp(100)
            size_hint_y: None
            height: 60
            padding: 500, 20
            MDRaisedButton:
                text: 'Cancelar'
                elevation_normal: 2
                oposite_colors: True
                pos_hint: {'x': .85}
                md_bg_color: 1, .1, .1, 1
            MDRaisedButton:
                text: 'Cadastrar'
                elevation_normal: 2
                oposite_colors: True
                pos_hint: {'x': .95}
                md_bg_color: .1, 1, .1, 1

<Field>:
    adaptive_size: True
    valor: input_text.hint_text
    tamanho: input_text.width
    focus: input_text.focus
    texto: input_text.text

    MDTextField:
        id: input_text
        mode: "rectangle"
        size_hint: None, None
        height: '30dp'
        width: root.tamanho
        hint_text: root.valor
        text: root.texto