<ProdutosView>:

    id: tela_produtos
    name: "produtos"
    text: title

    MDBoxLayout:
        orientation: 'vertical'
        padding: 0, 0, 0, 20

        BarraVoltar:
            id: title
            client: tela_produtos
            title: 'Cadastrar Produtos'
            right_action_items: [['arrow-left', lambda x: root.barra_voltar(), 'Voltar']]
            size_hint_y: None
            height: dp(60)

        MDGridLayout:
            cols: 2
            rows: 7
            orientation: 'tb-lr'
            spacing: dp(60), dp(20)
            padding: 40, 30, 50, 40
            col_default_width: dp(300)

            CampoTexto:
                id: campo_codigo
                hint_text: 'Código'
                on_text_validate:
                    root.number_validator(self, self.text)

            CampoTexto:
                id: campo_nome
                hint_text: 'Nome'
                on_text_validate:
                    root.text_validator(self, self.text)

            CampoTexto:
                id: campo_descricao
                hint_text: 'Descrição'
                multiline: True

            CampoTexto:
                id: campo_fab
                hint_text: 'Fabricante'
                on_text_validate:
                    root.text_validator(self, self.text)

            CampoTexto:
                id: campo_registro
                hint_text: 'Registro'
                required: False
                on_text_validate:
                    root.number_validator(self, self.text)

            MDBoxLayout:
                adaptive_height: True
                orientation: 'horizontal'
                spacing: dp(20)

                CampoTexto:
                    id: campo_peso
                    hint_text: 'Volume/Peso'
                    width: '130dp'
                    on_text_validate:
                        root.number_validator(self, self.text)

                MDBoxLayout:
                    orientation: 'vertical'
                    adaptive_size: False
                    MDLabel:
                        id: label_unidade
                    MDDropDownItem:
                        id: drop_unidade
                        pos_hint: {'center_x': .5, 'center_y': .5}
                        text: 'Unidade'
                        name: 'Unidade'
                        on_release: root.menu_unidade.open()
            Widget: #fecha a diagramação da coluna
            MDGridLayout:
                cols: 2
                MDBoxLayout:
                    orientation: 'vertical'
                    adaptive_size: False
                    MDLabel:
                        id: lbl_validade
                    MDDropDownItem:
                        canvas.before:
                            Color:
                                rgba: .1,.1,.1,.1
                            Rectangle:
                                pos: self.pos
                                size: self.width, self.height+sp(15)

                        id: drop_validade
                        text: "Validade"
                        name: "Validade"
                        on_release: root.show_date_picker()

                MDBoxLayout:
                    orientation: 'vertical'
                    adaptive_size: False
                    MDLabel:
                        id: _label
                    MDDropDownItem:
                        id: drop_tipo
                        pos_hint: {'center_x': .5, 'center_y': .5}
                        text: 'Tipo'
                        name: 'Tipo'
                        on_release: root.menu_tipo.open()

            MDBoxLayout:
                adaptive_height: True
                spacing: dp(50)

                CampoTexto:
                    id: campo_quantidade
                    hint_text: 'Quantidade'
                    width: '130dp'
                    on_text_validate:
                        root.number_validator(self, self.text)

                MDBoxLayout:
                    orientation: 'vertical'
                    adaptive_size: False
                    MDLabel:
                        id: _label

                    MDDropDownItem:
                        id: drop_embalagem
                        pos_hint: {'center_x': .5, 'center_y': .5}
                        text: 'Embalagem'
                        name: 'Embalagem'
                        on_release: root.menu_embalagem.open()

            MDBoxLayout:
                orientation: 'vertical'
                adaptive_size: True
                size_hint_x: None
                width: '310dp'
                MDLabel:
                    id: _label
                    size_hint: None, None
                    height: '20dp'
                    width: '310dp'
                    pos_hint: {'center_x': .5, 'center_y': .1}
                MDDropDownItem:
                    id: drop_forma
                    pos_hint: {'center_x': .5, 'center_y': .1}
                    text: 'Apresentação'
                    name: 'Apresentação'
                    on_release: root.menu_forma.open()

            CampoTexto:
                id: campo_fornecedor
                hint_text: 'Fornecedor'
                #tamanho: '310dp'

            MDBoxLayout:
                adaptive_height: True
                spacing: dp(50)

                CampoTexto:
                    id: campo_estoque
                    hint_text: 'Estoque'
                    width: '130dp'

                CampoTexto:
                    id: campo_lote
                    hint_text: 'Lote'
                    width: '130dp'

            MDBoxLayout:
                adaptive_height: True
                spacing: dp(50)

                CampoTexto:
                    id: campo_compra
                    hint_text: 'P. Compra'
                    width: '130dp'
                    input_filter: 'float'

                CampoTexto:
                    id: campo_preco
                    hint_text: 'Preço'
                    width: '130dp'
                    input_filter: 'float'

        BoxLayout:
            size_hint: .5, .5
            pos_hint:{'right': .9625, 'center_y': .5}
            padding: 20,20,20,20

            AnchorLayout:

                size_hint: .2,.2
                anchor_x:'right'
                anchor_y:'bottom'

                PharmaSysRsdBtn:
                    id: cancelar
                    text: 'Limpar'
                    md_bg_color: 1, .2, .2, 1
                    on_release: root.on_clear(root)

            AnchorLayout:
                anchor_x:'right'
                anchor_y:'bottom'
                size_hint: .2, .2

                PharmaSysRsdBtn:
                    id: cadastrar
                    text: 'Cadastrar'
                    md_bg_color: .2, .75, .2, 1
                    on_release: root.on_cadastrar()

<PharmaSysRsdBtn>:
    text: self.ids.mdbutton.text
    md_bg_color: self.ids.mdbutton.md_bg_color
    MDRaisedButton:
        id: mdbutton
        elevation_normal: 2
        oposite_colors: True
        text: root.text
        md_bg_color: root.md_bg_color
        size_hint: None, None
        width: dp(150) + (self.ids.lbl_txt.texture_size[0] - self.ids.lbl_txt.texture_size[0])
        height: dp(50)

<CampoTexto@MDTextField>:
    padding: 0,10,10,50
    mode:'rectangle'
    color_mode: 'custom'
    helper_text_mode: 'on_error'
    text_color: .15,.15,.95,.5
    current_hint_text_color: .15,.15,.15,.81
    size_hint: None, None
    multiline: False
    write_tab: False
    width: '310dp'
    height: self.height
    max_height: '80dp'


